--vim.keymap.set ("n", "<C-n>", vim.cmd.NERDTree)
--vim.keymap.set ("n", "<C-t>", vim.cmd.NERDTreeToggle)
--vim.keymap.set ("n", "<leader>n", vim.cmd.NERDTreeFocus)
vim.keymap.set ("n", "<C-n>", vim.cmd.NERDTreeToggle)
vim.keymap.set ("n", "<C-h>", vim.cmd.NERDTreeCWD)
vim.keymap.set ("n", "<C-f>", vim.cmd.NERDTreeFind)
vim.keymap.set ("n", "<leader>N", vim.cmd.NERDTreeCWD)
vim.keymap.set ("n", "<leader>F", vim.cmd.NERDTreeFind)
